[package]
name = "snitch-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.1.0"
tokio = { version = "1", features = ["full"] }
serde = {version = "*", features=["derive"]}
serde_json = "*"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
derive_more = "0.99.17"
alcoholic_jwt = "4091.0.0"
reqwest = "0.11.11"
mongodb = "2.3.0"
anyhow = "1.0"
futures = "0.3.21"
actix-cors = "0.6.2"
env_logger = "0.9.0"
log = "0.4.17"
chrono = {version="0.4.21", features=["serde"]}
snitch = {path="../snitch"}
async-trait = "0.1.57"
redis = {version="0.21.5", features=["tokio-comp", "streams"]}
actix-jwt-auth-middleware = {version="0.2.0", features=["use_jwt_traits"]}
exonum-crypto = "1.0.0"
jwt-compact = "0.6.0"
