[package]
name = "snitch-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.1.0"
tokio = "*"
serde = {version = "*", features=["derive"]}
serde_json = "*"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
derive_more = "0.99.17"
alcoholic_jwt = "4091.0.0"
reqwest = "0.11.11"
mongodb = "2.3.0"
anyhow = "1.0"
futures = "0.3.21"
actix-cors = "0.6.2"
