version: "3.9"
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kdjie234!
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kdjie234!
      ME_CONFIG_MONGODB_URL: mongodb://root:kdjie234!@mongo:27017/
