version: "3.9"
services:

  snitch-backend:
    build:
      context: ..
    ports:
      - "8081:8081"
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

